import type { Metadata } from "next";
import { Geist, Geist_Mono, Madimi_One } from "next/font/google";
import "./global-admin.css"
import React from "react";
import {SessionProvider} from "next-auth/react";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const madimiOne = Madimi_One({
    variable: "--font-madimi-one",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "Admin",
    description: "Generated by create next app",
};

export default function AdminLayout({
                                        children,
                                    }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="th">
        <body
            className={`${madimiOne.variable} antialiased`}
        >
        <SessionProvider>
            {children}
        </SessionProvider>
        </body>
        </html>
    );
}
