version: '3.8'

services:
  server:
    container_name: my-node-ts-server
    image: node:22
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    working_dir: /server
    volumes:
      - .:/server
      - /server/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL="prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODA4NmExMzItZjMxNi00OGQ4LWJhZjctYmYzY2M3MGQxMTZiIiwidGVuYW50X2lkIjoiZjU1MGU5N2JlZmIyMmQ4ZTVmODJjYTljZTNlZjE5OWYwYTM5OGRhZWQyYjI0OTViYTFmMGRmZjU5YzQwOGZjNiIsImludGVybmFsX3NlY3JldCI6IjY0N2FiYzQ4LTM1OGYtNDYwMS05NWFkLWJlNDZlODEyY2RhNyJ9.8-poyhMkk3VkHTybj3B2TruFXyrPo1OyGJqo6QOX2y8"

    command: npm run dev
